version: "3"
services:
  app:
    container_name: express-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - temporal-images:/app/dist/public/temporal
    env_file: 
      - .env

volumes:
  temporal-images:
  