name: CI

on:
  push:
    branches:
      - master



jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Build container image
        run: docker build --no-cache -t alexdevops111/unsplash:backend .  

      - name: Log in Docker Hub
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push alexdevops111/unsplash:backend

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build_and_push

    steps:
      - name: Deploy to Virtual Dedicated Server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.VDS_PASSWORD}}
          port: 22
          
          script: |
            # Login to Docker Hub
            sudo docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}

            # Stop running container
            sudo docker stop express-api

            # Remove old container
            sudo docker rm express-api 

            # Remove old image
            sudo docker rmi alexdevops111/unsplash:backend

            # Pull from Docker Hub
            sudo docker pull alexdevops111/unsplash:backend

            # Run a new container from a new image
            sudo docker run -d -p 8080:8080 -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} -e CLOUDINARY_NAME=${{ secrets.CLOUDINARY_NAME }} -e CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }} -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e PORT=${{ secrets.PORT }} --name express-api alexdevops111/unsplash:backend 
